#### dowanload
pip install huggingface_hub
export HF_TOKEN=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
huggingface-cli login --token $HF_TOKEN

mkdir ./msdata/split_small
huggingface-cli download wei682/split_small --repo-type dataset --local-dir ./msdata/split_small
# huggingface-cli download wei682/amazon-grpo --repo-type dataset --local-dir /cpfs01/shared/llm_ddd/zhangyulong/sa_work/msdata/grpo_data


mkdir ./wei682/split_small_small
huggingface-cli download wei682/split_small_small --repo-type dataset --local-dir ./msdata/split_small_small



#### upload
pip install huggingface_hub
export HF_TOKEN=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
huggingface-cli login --token $HF_TOKEN

huggingface-cli upload split-small-qwen merged_data.json --repo-type dataset

huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_All_Beauty_description_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_All_Beauty_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_All_Beauty_feature_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_All_Beauty_main_category_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_All_Beauty_price_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_All_Beauty_Store_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_All_Beauty_title_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Amazon_Fashion_description_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Amazon_Fashion_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Amazon_Fashion_feature_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Amazon_Fashion_main_category_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Amazon_Fashion_price_sftdata_att_train_0.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Amazon_Fashion_Store_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Amazon_Fashion_title_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Appliances_description_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Appliances_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Appliances_feature_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Appliances_price_sftdata_att_train_30.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Appliances_Store_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Appliances_title_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Arts_Crafts_and_Sewing_description_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Arts_Crafts_and_Sewing_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Arts_Crafts_and_Sewing_feature_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Arts_Crafts_and_Sewing_main_category_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Arts_Crafts_and_Sewing_price_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Arts_Crafts_and_Sewing_Store_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Arts_Crafts_and_Sewing_title_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Automotive_description_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Automotive_details_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Automotive_feature_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Automotive_main_category_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Automotive_price_sftdata_att_train_0.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Automotive_Store_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Automotive_title_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Baby_Products_description_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Baby_Products_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Baby_Products_feature_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Baby_Products_main_category_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Baby_Products_price_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Baby_Products_Store_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Baby_Products_title_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Beauty_and_Personal_Care_description_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Beauty_and_Personal_Care_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Beauty_and_Personal_Care_feature_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Beauty_and_Personal_Care_main_category_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Beauty_and_Personal_Care_price_sftdata_att_train_80.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Beauty_and_Personal_Care_Store_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Beauty_and_Personal_Care_title_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Books_description_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Books_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Books_feature_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Books_main_category_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Books_price_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Books_Store_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Books_title_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Books_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Books_feature_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Books_main_category_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Books_price_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Books_Store_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Books_title_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_CDs_and_Vinyl_description_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_CDs_and_Vinyl_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_CDs_and_Vinyl_feature_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_CDs_and_Vinyl_main_category_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_CDs_and_Vinyl_price_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_CDs_and_Vinyl_Store_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_CDs_and_Vinyl_title_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Cell_Phones_and_Accessories_description_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Cell_Phones_and_Accessories_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Cell_Phones_and_Accessories_feature_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Cell_Phones_and_Accessories_main_category_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Cell_Phones_and_Accessories_price_sftdata_att_train_0.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Cell_Phones_and_Accessories_Store_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Cell_Phones_and_Accessories_title_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Clothing_Shoes_and_Jewelry_description_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Clothing_Shoes_and_Jewelry_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Clothing_Shoes_and_Jewelry_feature_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Clothing_Shoes_and_Jewelry_main_category_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Clothing_Shoes_and_Jewelry_price_sftdata_att_train_30.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Clothing_Shoes_and_Jewelry_Store_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Clothing_Shoes_and_Jewelry_title_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Digital_Music_description_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Digital_Music_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Digital_Music_feature_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Digital_Music_main_category_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Digital_Music_price_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Digital_Music_Store_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Digital_Music_title_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Electronics_description_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Electronics_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Electronics_feature_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Electronics_main_category_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Electronics_price_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Electronics_Store_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Electronics_title_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Gift_Cards_description_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Gift_Cards_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Gift_Cards_feature_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Gift_Cards_main_category_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Gift_Cards_price_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Gift_Cards_Store_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Gift_Cards_title_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Grocery_and_Gourmet_Food_description_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Grocery_and_Gourmet_Food_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Grocery_and_Gourmet_Food_feature_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Grocery_and_Gourmet_Food_main_category_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Grocery_and_Gourmet_Food_price_sftdata_att_filte_train_80.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Grocery_and_Gourmet_Food_price_sftdata_att_train_80.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Grocery_and_Gourmet_Food_Store_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Grocery_and_Gourmet_Food_title_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Handmade_Products_description_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Handmade_Products_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Handmade_Products_feature_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Handmade_Products_main_category_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Handmade_Products_price_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Handmade_Products_Store_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Handmade_Products_title_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Health_and_Household_description_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Health_and_Household_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Health_and_Household_feature_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Health_and_Household_main_category_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Health_and_Household_price_sftdata_att_train_29.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Health_and_Household_Store_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Health_and_Household_title_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Health_and_Personal_Care_description_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Health_and_Personal_Care_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Health_and_Personal_Care_feature_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Health_and_Personal_Care_main_category_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Health_and_Personal_Care_price_sftdata_att_train_30.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Health_and_Personal_Care_Store_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Health_and_Personal_Care_title_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Home_and_Kitchen_description_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Home_and_Kitchen_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Home_and_Kitchen_feature_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Home_and_Kitchen_main_category_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Home_and_Kitchen_price_sftdata_att_train_20.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Home_and_Kitchen_Store_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Home_and_Kitchen_title_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Industrial_and_Scientific_description_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Industrial_and_Scientific_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Industrial_and_Scientific_feature_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Industrial_and_Scientific_main_category_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Industrial_and_Scientific_price_sftdata_att_train_30.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Industrial_and_Scientific_Store_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Industrial_and_Scientific_title_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Kindle_Store_description_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Kindle_Store_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Kindle_Store_feature_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Kindle_Store_main_category_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Kindle_Store_price_sftdata_att_train_20.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Kindle_Store_Store_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Kindle_Store_title_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Magazine_Subscriptions_description_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Magazine_Subscriptions_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Magazine_Subscriptions_feature_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Magazine_Subscriptions_main_category_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Magazine_Subscriptions_price_sftdata_att_train_80.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Magazine_Subscriptions_Store_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Magazine_Subscriptions_title_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Movies_and_TV_description_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Movies_and_TV_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Movies_and_TV_feature_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Movies_and_TV_main_category_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Movies_and_TV_price_sftdata_att_train_80.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Movies_and_TV_Store_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Movies_and_TV_title_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Musical_Instruments_description_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Musical_Instruments_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Musical_Instruments_feature_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Musical_Instruments_main_category_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Musical_Instruments_price_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Musical_Instruments_Store_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Musical_Instruments_title_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Office_Products_description_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Office_Products_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Office_Products_feature_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Office_Products_main_category_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Office_Products_price_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Office_Products_Store_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Office_Products_title_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Patio_Lawn_and_Garden_description_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Patio_Lawn_and_Garden_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Patio_Lawn_and_Garden_feature_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Patio_Lawn_and_Garden_main_category_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Patio_Lawn_and_Garden_price_sftdata_att_train_80.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Patio_Lawn_and_Garden_Store_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Patio_Lawn_and_Garden_title_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Pet_Supplies_description_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Pet_Supplies_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Pet_Supplies_feature_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Pet_Supplies_main_category_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Pet_Supplies_price_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Pet_Supplies_Store_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Pet_Supplies_title_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Software_description_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Software_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Software_feature_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Software_main_category_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Software_price_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Software_Store_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Software_title_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Sports_and_Outdoors_description_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Sports_and_Outdoors_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Sports_and_Outdoors_feature_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Sports_and_Outdoors_main_category_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Sports_and_Outdoors_price_sftdata_att_train_30.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Sports_and_Outdoors_Store_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Sports_and_Outdoors_title_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Subscription_Boxes_description_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Subscription_Boxes_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Subscription_Boxes_feature_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Subscription_Boxes_main_category_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Subscription_Boxes_price_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Subscription_Boxes_Store_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Subscription_Boxes_title_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Tools_and_Home_Improvement_description_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Tools_and_Home_Improvement_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Tools_and_Home_Improvement_feature_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Tools_and_Home_Improvement_main_category_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Tools_and_Home_Improvement_price_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Tools_and_Home_Improvement_Store_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Tools_and_Home_Improvement_title_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Toys_and_Games_description_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Toys_and_Games_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Toys_and_Games_feature_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Toys_and_Games_main_category_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Toys_and_Games_price_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Toys_and_Games_Store_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Toys_and_Games_title_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Video_Games_description_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Video_Games_details_sftdata_att_train_400.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Video_Games_feature_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Video_Games_main_category_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Video_Games_price_sftdata_att_train_30.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Video_Games_Store_sftdata_att_train_180.json --repo-type dataset
huggingface-cli upload split-small-small-qwen qwen_meta_Video_Games_title_sftdata_att_train_400.json --repo-type dataset



huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset
huggingface-cli upload split-small-small-qwen merged_data.json --repo-type dataset


